[package]
name = "lumen-rag"
version = "0.1.0"
edition = "2021"
description = "A modular, database-agnostic RAG framework for Rust supporting MongoDB, Qdrant, and SAP HANA Cloud."
license = "MIT"
repository = "https://github.com/Maki-Grz/lumen-rag"
homepage = "https://github.com/Maki-Grz/lumen-rag"
documentation = "https://docs.rs/lumen-rag"
readme = "README.md"
keywords = ["rag", "llm", "search", "vector-database", "nlp", "sap-hana"]
categories = ["science", "web-programming"]
exclude = ["/tests", "/examples", ".github"]

[lib]
name = "lumen_rag"
path = "src/lib.rs"

[features]
default = ["mongodb"]
mongodb = ["dep:mongodb"]
qdrant = ["dep:qdrant-client"]
hana = ["dep:hdbconnect"]

[dependencies]
anyhow = "1.0.95"
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
async-trait = "0.1.86"
futures = "0.3.31"
futures-util = "0.3.31"
twox-hash = "2.1.2"
regex = "1.11.2"
rayon = "1.11.0"
tokio = { version = "1.43.0", features = ["full"] }
reqwest = { version = "0.12.12", features = ["json"] }
candle-core = { version = "0.9.1" }
candle-transformers = { version = "0.9.1" }
candle-nn = "0.9.1"
hf-hub = "0.4.3"
tokenizers = "0.22.0"
mongodb = { version = "3.1.1", features = ["zstd-compression"], optional = true }
qdrant-client = { version = "1.12.0", optional = true }
hdbconnect = { version = "0.32.0", optional = true }

[dev-dependencies]
actix-web = "4.9.0"
actix-rt = "2.10.0"
actix-cors = "0.7.1"
dotenv = "0.15.0"
tracing-subscriber = "0.3.20"
qdrant-client = "1.12"
